version: '2'
services:
  db:
    image: mysql:5.7
    user: "1000:50" # needed on Mac
    volumes:
      - "./.data/db:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMe
      MYSQL_DATABASE: mojito
      MYSQL_USER: mojito
      MYSQL_PASSWORD: ChangeMe
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      - --innodb_use_native_aio=0 # needed on Mac
  webapp:
    depends_on:
      - db
    build:
      dockerfile: docker/Dockerfile-bk8
      context: ../
#    image: aurambaj/mojito-webapp-bk8:latest
    links:
      - db
    ports:
      - "8080:8080"
    restart: always
    environment:
#      JAVA_OPTS: '-Xms2g'
      SPRING_APPLICATION_JSON: '{
      "spring.flyway.enabled": "true",
      "l10n.flyway.clean" : "false",
      "spring.jpa.database-platform" : "org.hibernate.dialect.MySQLDialect",
      "spring.jpa.hibernate.ddl-auto" : "none",
      "spring.datasource.url" : "jdbc:mysql://db:3306/mojito?characterEncoding=UTF-8&useUnicode=true",
      "spring.datasource.username" : "mojito",
      "spring.datasource.password" : "ChangeMe",
      "spring.datasource.driverClassName" : "com.mysql.cj.jdbc.Driver"
      }'
