# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: mojito
email: mojito-global@googlegroups.com
description: > # this means to ignore newlines until "baseurl:"
  An open source automation platform that enables continuous localization for software development
baseurl: "" # the subpath of your site, e.g. /blog
url: https://pinterest.github.io/mojito/ # the base hostname & protocol for your site
mojito_green: <span><font color="green">mojito</font><span>
github_url: https://github.com/pinterest/mojito
github_username:  mojito
# Build settings
markdown: kramdown
exclude: ["node_modules/", "webapp/"]
collections:
  docs:
    output: true
google_analytics: UA-83813115-1
